### ISSUE TITLE
Dartmouth Park Hill

### ISSUE THREAD

**Issue by jamieparkinson** [jrans/flat-search#1]
**Price:** £340pw

**Listing URL:** http://www.stonehouse-estates.co.uk/property/residential/for-rent/london/archway/dartmouth-park/dartmouth-park-hill/100866003306

**Cons**
  - Bad website

**Todo:**
- [ ] Arrange viewing
- [ ] Go to viewing
- [ ] Make offer

**Comment by jrans** [comment]
1 bedroom ? @jamieparkinson  Can i close?

**Comment by jamieparkinson** [comment]
Oops yes
