### ISSUE TITLE
Dartmouth Park Hill

### ISSUE THREAD

**Issue by jamieparkinson** [jrans/flat-search#11]
**Price:** £340pw

**Listing URL:** http://www.stonehouse-estates.co.uk/property/residential/for-rent/london/archway/dartmouth-park/dartmouth-park-hill/100866000800

**Pros:**
 - Looks nicely decorated
 - I know there are great views on this road
 
**Cons:** 
 - Furnishing not definite

**Todo:**
- [x] Arrange viewing
- [x] Go to viewing
- [ ] Make offer

**Comment by jamieparkinson** [comment]
@jamieparkinson going to a viewing at 17:00 today

**Comment by jamieparkinson** [comment]
It's OK but nothing great. It feels quite dingy inside. Nice big open kitchen and one v large bedroom, one rather small room. Worth noting that it's really quite cheap though! Sort of see it as a 'backup'

**Comment by jrans** [comment]
Ok leaving open, but yes onto the others!
