### ISSUE TITLE
Lady Margaret Road

### ISSUE THREAD

**Issue by jrans** [jrans/flat-search#14]
**Price:** 385pw

**Listing URL:** http://www.rochesterplace.co.uk/property/lady-margaret-road-tufnell-park-n19/roch-000278/1

**Pros:**
 - Two gardens,
 - Down stairs
 - Lots of room
 - mOdern
 
**Cons:** 
 - Over budget

**Todo:**
- [x] Arrange viewing
- [x] Go to viewing
- [ ] Make offer

**Comment by jamieparkinson** [comment]
Too £££££
