### ISSUE TITLE
Maycroft, Lady Margaret Road

### ISSUE THREAD

**Issue by jamieparkinson** [jrans/flat-search#5]
**Price:** £360pw

**Listing URL:** http://www.rightmove.co.uk/property-to-rent/property-61001047.html

**Pros:**
 - excellent location
 - big reception room
 
**Cons:** 
 - pictures unclear
 - in a block of flats if that is a negative

**Todo:**
- [ ] Arrange viewing
- [ ] Go to viewing
- [ ] Make offer

**Comment by jrans** [comment]
Like but second bedroom?

**Comment by jamieparkinson** [comment]
Oops I can't read

**Comment by jamieparkinson** [comment]
Sorry didn't mean to close

**Comment by jamieparkinson** [comment]
2nd bedroom is pic number 4 right?
