### ISSUE TITLE
Pemberton Terrace

### ISSUE THREAD

**Issue by jamieparkinson** [jrans/flat-search#8]
**Price:** £360pw

**Listing URL:** http://www.rightmove.co.uk/property-to-rent/property-37413945.html

**Pros:**
 - Looks great!
 
**Cons:** 
 - I think one bedroom is tiny...

**Todo:**
- [x] Arrange viewing
- [ ] Go to viewing
- [ ] Make offer

**Comment by jrans** [comment]
looks allwhite!

**Comment by jamieparkinson** [comment]
Viewing booked @ 17:30 on Monday

**Comment by jamieparkinson** [comment]
Saw, wasn't great
