### ISSUE TITLE
Ospringe Road

### ISSUE THREAD

**Issue by jrans** [jrans/flat-search#9]
**Price:** 380pw but originally listed at 370

**Listing URL:** http://www.rightmove.co.uk/property-to-rent/property-61053124.html

**Pros:**
 - Furnished
 - Wooden Floors
 - Loft conversion
 - Beautiful
 
**Cons:** 
 - top end of budget

**Todo:**
- [x] Arrange viewing
- [x] Go to viewing
- [x] Make offer

![Ospringe Road](http://media.rightmove.co.uk/dir/97k/96542/61053124/96542_ROCH_000266_IMG_02_0000_max_656x437.jpg)

![Floor Plan](http://media.rightmove.co.uk/97k/96542/61053124/96542_ROCH_000266_FLP_01_0000_max_900x900.jpg)

**Comment by jamieparkinson** [comment]
Worth arranging a viewing to see what bedroom 2 is really like. I can assure you that having a micro room is no fun tho.

**Comment by jrans** [comment]
Fair, I'd sacrifice my room if nice place!

**Comment by jamieparkinson** [comment]
Yeah boiiiii
